#ifndef HOST_BLE_ATT_H_
#define HOST_BLE_ATT_H_

enum {
    BLE_ATT_ERR_INVALID_OFFSET = 1,
    BLE_ATT_ERR_INVALID_ATTR_VALUE_LEN,
    BLE_ATT_ERR_UNLIKELY,
    BLE_ATT_ERR_INSUFFICIENT_RES,
};

#endif
