import codecs
import json
import sys


top = """
/*
 * This file is automatically generated. DO NOT MODIFY!
 */

#ifndef OMNITRIX_UUID_H_
#define OMNITRIX_UUID_H_
""".lstrip()

bottom = """
#endif
"""

with open(sys.argv[1], "r") as fin:
    data = {k: v for k, v in json.load(fin).items() if k.startswith("OMNITRIX_") and k.endswith("_UUID")}

with open(sys.argv[2], "w") as fout:
    print(top, file=fout)
    for k, v in data.items():
        init = ", ".join(hex(x) for x in codecs.decode(v.replace("-", ""), "hex")[::-1])
        print(f"#define CONFIG_{k}_INIT BLE_UUID128_INIT({init})", file=fout)
    print(bottom, file=fout)
