/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: j2534.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "j2534.pb-c.h"
void   message__init
                     (Message         *message)
{
  static const Message init_value = MESSAGE__INIT;
  *message = init_value;
}
size_t message__get_packed_size
                     (const Message *message)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message__pack
                     (const Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message__pack_to_buffer
                     (const Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Message *
       message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Message *)
     protobuf_c_message_unpack (&message__descriptor,
                                allocator, len, data);
}
void   message__free_unpacked
                     (Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   config__init
                     (Config         *message)
{
  static const Config init_value = CONFIG__INIT;
  *message = init_value;
}
size_t config__get_packed_size
                     (const Config *message)
{
  assert(message->base.descriptor == &config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t config__pack
                     (const Config *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t config__pack_to_buffer
                     (const Config *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Config *
       config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Config *)
     protobuf_c_message_unpack (&config__descriptor,
                                allocator, len, data);
}
void   config__free_unpacked
                     (Config *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   base_request__init
                     (BaseRequest         *message)
{
  static const BaseRequest init_value = BASE_REQUEST__INIT;
  *message = init_value;
}
size_t base_request__get_packed_size
                     (const BaseRequest *message)
{
  assert(message->base.descriptor == &base_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t base_request__pack
                     (const BaseRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &base_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t base_request__pack_to_buffer
                     (const BaseRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &base_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BaseRequest *
       base_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BaseRequest *)
     protobuf_c_message_unpack (&base_request__descriptor,
                                allocator, len, data);
}
void   base_request__free_unpacked
                     (BaseRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &base_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   base_response__init
                     (BaseResponse         *message)
{
  static const BaseResponse init_value = BASE_RESPONSE__INIT;
  *message = init_value;
}
size_t base_response__get_packed_size
                     (const BaseResponse *message)
{
  assert(message->base.descriptor == &base_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t base_response__pack
                     (const BaseResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &base_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t base_response__pack_to_buffer
                     (const BaseResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &base_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BaseResponse *
       base_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BaseResponse *)
     protobuf_c_message_unpack (&base_response__descriptor,
                                allocator, len, data);
}
void   base_response__free_unpacked
                     (BaseResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &base_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   connect_request__init
                     (ConnectRequest         *message)
{
  static const ConnectRequest init_value = CONNECT_REQUEST__INIT;
  *message = init_value;
}
size_t connect_request__get_packed_size
                     (const ConnectRequest *message)
{
  assert(message->base.descriptor == &connect_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t connect_request__pack
                     (const ConnectRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &connect_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t connect_request__pack_to_buffer
                     (const ConnectRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &connect_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ConnectRequest *
       connect_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ConnectRequest *)
     protobuf_c_message_unpack (&connect_request__descriptor,
                                allocator, len, data);
}
void   connect_request__free_unpacked
                     (ConnectRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &connect_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   connect_response__init
                     (ConnectResponse         *message)
{
  static const ConnectResponse init_value = CONNECT_RESPONSE__INIT;
  *message = init_value;
}
size_t connect_response__get_packed_size
                     (const ConnectResponse *message)
{
  assert(message->base.descriptor == &connect_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t connect_response__pack
                     (const ConnectResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &connect_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t connect_response__pack_to_buffer
                     (const ConnectResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &connect_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ConnectResponse *
       connect_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ConnectResponse *)
     protobuf_c_message_unpack (&connect_response__descriptor,
                                allocator, len, data);
}
void   connect_response__free_unpacked
                     (ConnectResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &connect_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   disconnect_request__init
                     (DisconnectRequest         *message)
{
  static const DisconnectRequest init_value = DISCONNECT_REQUEST__INIT;
  *message = init_value;
}
size_t disconnect_request__get_packed_size
                     (const DisconnectRequest *message)
{
  assert(message->base.descriptor == &disconnect_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t disconnect_request__pack
                     (const DisconnectRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &disconnect_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t disconnect_request__pack_to_buffer
                     (const DisconnectRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &disconnect_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DisconnectRequest *
       disconnect_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DisconnectRequest *)
     protobuf_c_message_unpack (&disconnect_request__descriptor,
                                allocator, len, data);
}
void   disconnect_request__free_unpacked
                     (DisconnectRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &disconnect_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   read_request__init
                     (ReadRequest         *message)
{
  static const ReadRequest init_value = READ_REQUEST__INIT;
  *message = init_value;
}
size_t read_request__get_packed_size
                     (const ReadRequest *message)
{
  assert(message->base.descriptor == &read_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t read_request__pack
                     (const ReadRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &read_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t read_request__pack_to_buffer
                     (const ReadRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &read_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReadRequest *
       read_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReadRequest *)
     protobuf_c_message_unpack (&read_request__descriptor,
                                allocator, len, data);
}
void   read_request__free_unpacked
                     (ReadRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &read_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   read_response__init
                     (ReadResponse         *message)
{
  static const ReadResponse init_value = READ_RESPONSE__INIT;
  *message = init_value;
}
size_t read_response__get_packed_size
                     (const ReadResponse *message)
{
  assert(message->base.descriptor == &read_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t read_response__pack
                     (const ReadResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &read_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t read_response__pack_to_buffer
                     (const ReadResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &read_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReadResponse *
       read_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReadResponse *)
     protobuf_c_message_unpack (&read_response__descriptor,
                                allocator, len, data);
}
void   read_response__free_unpacked
                     (ReadResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &read_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   write_request__init
                     (WriteRequest         *message)
{
  static const WriteRequest init_value = WRITE_REQUEST__INIT;
  *message = init_value;
}
size_t write_request__get_packed_size
                     (const WriteRequest *message)
{
  assert(message->base.descriptor == &write_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t write_request__pack
                     (const WriteRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &write_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t write_request__pack_to_buffer
                     (const WriteRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &write_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WriteRequest *
       write_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WriteRequest *)
     protobuf_c_message_unpack (&write_request__descriptor,
                                allocator, len, data);
}
void   write_request__free_unpacked
                     (WriteRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &write_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   write_response__init
                     (WriteResponse         *message)
{
  static const WriteResponse init_value = WRITE_RESPONSE__INIT;
  *message = init_value;
}
size_t write_response__get_packed_size
                     (const WriteResponse *message)
{
  assert(message->base.descriptor == &write_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t write_response__pack
                     (const WriteResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &write_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t write_response__pack_to_buffer
                     (const WriteResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &write_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WriteResponse *
       write_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WriteResponse *)
     protobuf_c_message_unpack (&write_response__descriptor,
                                allocator, len, data);
}
void   write_response__free_unpacked
                     (WriteResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &write_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   start_periodic_request__init
                     (StartPeriodicRequest         *message)
{
  static const StartPeriodicRequest init_value = START_PERIODIC_REQUEST__INIT;
  *message = init_value;
}
size_t start_periodic_request__get_packed_size
                     (const StartPeriodicRequest *message)
{
  assert(message->base.descriptor == &start_periodic_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t start_periodic_request__pack
                     (const StartPeriodicRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &start_periodic_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t start_periodic_request__pack_to_buffer
                     (const StartPeriodicRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &start_periodic_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StartPeriodicRequest *
       start_periodic_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StartPeriodicRequest *)
     protobuf_c_message_unpack (&start_periodic_request__descriptor,
                                allocator, len, data);
}
void   start_periodic_request__free_unpacked
                     (StartPeriodicRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &start_periodic_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   start_periodic_response__init
                     (StartPeriodicResponse         *message)
{
  static const StartPeriodicResponse init_value = START_PERIODIC_RESPONSE__INIT;
  *message = init_value;
}
size_t start_periodic_response__get_packed_size
                     (const StartPeriodicResponse *message)
{
  assert(message->base.descriptor == &start_periodic_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t start_periodic_response__pack
                     (const StartPeriodicResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &start_periodic_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t start_periodic_response__pack_to_buffer
                     (const StartPeriodicResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &start_periodic_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StartPeriodicResponse *
       start_periodic_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StartPeriodicResponse *)
     protobuf_c_message_unpack (&start_periodic_response__descriptor,
                                allocator, len, data);
}
void   start_periodic_response__free_unpacked
                     (StartPeriodicResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &start_periodic_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stop_periodic_request__init
                     (StopPeriodicRequest         *message)
{
  static const StopPeriodicRequest init_value = STOP_PERIODIC_REQUEST__INIT;
  *message = init_value;
}
size_t stop_periodic_request__get_packed_size
                     (const StopPeriodicRequest *message)
{
  assert(message->base.descriptor == &stop_periodic_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stop_periodic_request__pack
                     (const StopPeriodicRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stop_periodic_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stop_periodic_request__pack_to_buffer
                     (const StopPeriodicRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stop_periodic_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StopPeriodicRequest *
       stop_periodic_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StopPeriodicRequest *)
     protobuf_c_message_unpack (&stop_periodic_request__descriptor,
                                allocator, len, data);
}
void   stop_periodic_request__free_unpacked
                     (StopPeriodicRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stop_periodic_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   start_filter_request__init
                     (StartFilterRequest         *message)
{
  static const StartFilterRequest init_value = START_FILTER_REQUEST__INIT;
  *message = init_value;
}
size_t start_filter_request__get_packed_size
                     (const StartFilterRequest *message)
{
  assert(message->base.descriptor == &start_filter_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t start_filter_request__pack
                     (const StartFilterRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &start_filter_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t start_filter_request__pack_to_buffer
                     (const StartFilterRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &start_filter_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StartFilterRequest *
       start_filter_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StartFilterRequest *)
     protobuf_c_message_unpack (&start_filter_request__descriptor,
                                allocator, len, data);
}
void   start_filter_request__free_unpacked
                     (StartFilterRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &start_filter_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   start_filter_response__init
                     (StartFilterResponse         *message)
{
  static const StartFilterResponse init_value = START_FILTER_RESPONSE__INIT;
  *message = init_value;
}
size_t start_filter_response__get_packed_size
                     (const StartFilterResponse *message)
{
  assert(message->base.descriptor == &start_filter_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t start_filter_response__pack
                     (const StartFilterResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &start_filter_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t start_filter_response__pack_to_buffer
                     (const StartFilterResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &start_filter_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StartFilterResponse *
       start_filter_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StartFilterResponse *)
     protobuf_c_message_unpack (&start_filter_response__descriptor,
                                allocator, len, data);
}
void   start_filter_response__free_unpacked
                     (StartFilterResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &start_filter_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stop_filter_request__init
                     (StopFilterRequest         *message)
{
  static const StopFilterRequest init_value = STOP_FILTER_REQUEST__INIT;
  *message = init_value;
}
size_t stop_filter_request__get_packed_size
                     (const StopFilterRequest *message)
{
  assert(message->base.descriptor == &stop_filter_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stop_filter_request__pack
                     (const StopFilterRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stop_filter_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stop_filter_request__pack_to_buffer
                     (const StopFilterRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stop_filter_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StopFilterRequest *
       stop_filter_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StopFilterRequest *)
     protobuf_c_message_unpack (&stop_filter_request__descriptor,
                                allocator, len, data);
}
void   stop_filter_request__free_unpacked
                     (StopFilterRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stop_filter_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   set_voltage_request__init
                     (SetVoltageRequest         *message)
{
  static const SetVoltageRequest init_value = SET_VOLTAGE_REQUEST__INIT;
  *message = init_value;
}
size_t set_voltage_request__get_packed_size
                     (const SetVoltageRequest *message)
{
  assert(message->base.descriptor == &set_voltage_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_voltage_request__pack
                     (const SetVoltageRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &set_voltage_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_voltage_request__pack_to_buffer
                     (const SetVoltageRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &set_voltage_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetVoltageRequest *
       set_voltage_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetVoltageRequest *)
     protobuf_c_message_unpack (&set_voltage_request__descriptor,
                                allocator, len, data);
}
void   set_voltage_request__free_unpacked
                     (SetVoltageRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &set_voltage_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   read_version_response__init
                     (ReadVersionResponse         *message)
{
  static const ReadVersionResponse init_value = READ_VERSION_RESPONSE__INIT;
  *message = init_value;
}
size_t read_version_response__get_packed_size
                     (const ReadVersionResponse *message)
{
  assert(message->base.descriptor == &read_version_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t read_version_response__pack
                     (const ReadVersionResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &read_version_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t read_version_response__pack_to_buffer
                     (const ReadVersionResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &read_version_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReadVersionResponse *
       read_version_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReadVersionResponse *)
     protobuf_c_message_unpack (&read_version_response__descriptor,
                                allocator, len, data);
}
void   read_version_response__free_unpacked
                     (ReadVersionResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &read_version_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_error_response__init
                     (GetErrorResponse         *message)
{
  static const GetErrorResponse init_value = GET_ERROR_RESPONSE__INIT;
  *message = init_value;
}
size_t get_error_response__get_packed_size
                     (const GetErrorResponse *message)
{
  assert(message->base.descriptor == &get_error_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_error_response__pack
                     (const GetErrorResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_error_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_error_response__pack_to_buffer
                     (const GetErrorResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_error_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetErrorResponse *
       get_error_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetErrorResponse *)
     protobuf_c_message_unpack (&get_error_response__descriptor,
                                allocator, len, data);
}
void   get_error_response__free_unpacked
                     (GetErrorResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_error_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ioctl_request__init
                     (IoctlRequest         *message)
{
  static const IoctlRequest init_value = IOCTL_REQUEST__INIT;
  *message = init_value;
}
size_t ioctl_request__get_packed_size
                     (const IoctlRequest *message)
{
  assert(message->base.descriptor == &ioctl_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ioctl_request__pack
                     (const IoctlRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ioctl_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ioctl_request__pack_to_buffer
                     (const IoctlRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ioctl_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IoctlRequest *
       ioctl_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IoctlRequest *)
     protobuf_c_message_unpack (&ioctl_request__descriptor,
                                allocator, len, data);
}
void   ioctl_request__free_unpacked
                     (IoctlRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ioctl_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ioctl_response__init
                     (IoctlResponse         *message)
{
  static const IoctlResponse init_value = IOCTL_RESPONSE__INIT;
  *message = init_value;
}
size_t ioctl_response__get_packed_size
                     (const IoctlResponse *message)
{
  assert(message->base.descriptor == &ioctl_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ioctl_response__pack
                     (const IoctlResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ioctl_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ioctl_response__pack_to_buffer
                     (const IoctlResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ioctl_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IoctlResponse *
       ioctl_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IoctlResponse *)
     protobuf_c_message_unpack (&ioctl_response__descriptor,
                                allocator, len, data);
}
void   ioctl_response__free_unpacked
                     (IoctlResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ioctl_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ioctl_get_config_request__init
                     (IoctlGetConfigRequest         *message)
{
  static const IoctlGetConfigRequest init_value = IOCTL_GET_CONFIG_REQUEST__INIT;
  *message = init_value;
}
size_t ioctl_get_config_request__get_packed_size
                     (const IoctlGetConfigRequest *message)
{
  assert(message->base.descriptor == &ioctl_get_config_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ioctl_get_config_request__pack
                     (const IoctlGetConfigRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ioctl_get_config_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ioctl_get_config_request__pack_to_buffer
                     (const IoctlGetConfigRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ioctl_get_config_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IoctlGetConfigRequest *
       ioctl_get_config_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IoctlGetConfigRequest *)
     protobuf_c_message_unpack (&ioctl_get_config_request__descriptor,
                                allocator, len, data);
}
void   ioctl_get_config_request__free_unpacked
                     (IoctlGetConfigRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ioctl_get_config_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ioctl_get_config_response__init
                     (IoctlGetConfigResponse         *message)
{
  static const IoctlGetConfigResponse init_value = IOCTL_GET_CONFIG_RESPONSE__INIT;
  *message = init_value;
}
size_t ioctl_get_config_response__get_packed_size
                     (const IoctlGetConfigResponse *message)
{
  assert(message->base.descriptor == &ioctl_get_config_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ioctl_get_config_response__pack
                     (const IoctlGetConfigResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ioctl_get_config_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ioctl_get_config_response__pack_to_buffer
                     (const IoctlGetConfigResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ioctl_get_config_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IoctlGetConfigResponse *
       ioctl_get_config_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IoctlGetConfigResponse *)
     protobuf_c_message_unpack (&ioctl_get_config_response__descriptor,
                                allocator, len, data);
}
void   ioctl_get_config_response__free_unpacked
                     (IoctlGetConfigResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ioctl_get_config_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ioctl_set_config_request__init
                     (IoctlSetConfigRequest         *message)
{
  static const IoctlSetConfigRequest init_value = IOCTL_SET_CONFIG_REQUEST__INIT;
  *message = init_value;
}
size_t ioctl_set_config_request__get_packed_size
                     (const IoctlSetConfigRequest *message)
{
  assert(message->base.descriptor == &ioctl_set_config_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ioctl_set_config_request__pack
                     (const IoctlSetConfigRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ioctl_set_config_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ioctl_set_config_request__pack_to_buffer
                     (const IoctlSetConfigRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ioctl_set_config_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IoctlSetConfigRequest *
       ioctl_set_config_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IoctlSetConfigRequest *)
     protobuf_c_message_unpack (&ioctl_set_config_request__descriptor,
                                allocator, len, data);
}
void   ioctl_set_config_request__free_unpacked
                     (IoctlSetConfigRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ioctl_set_config_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ioctl_read_vbatt_response__init
                     (IoctlReadVbattResponse         *message)
{
  static const IoctlReadVbattResponse init_value = IOCTL_READ_VBATT_RESPONSE__INIT;
  *message = init_value;
}
size_t ioctl_read_vbatt_response__get_packed_size
                     (const IoctlReadVbattResponse *message)
{
  assert(message->base.descriptor == &ioctl_read_vbatt_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ioctl_read_vbatt_response__pack
                     (const IoctlReadVbattResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ioctl_read_vbatt_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ioctl_read_vbatt_response__pack_to_buffer
                     (const IoctlReadVbattResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ioctl_read_vbatt_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IoctlReadVbattResponse *
       ioctl_read_vbatt_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IoctlReadVbattResponse *)
     protobuf_c_message_unpack (&ioctl_read_vbatt_response__descriptor,
                                allocator, len, data);
}
void   ioctl_read_vbatt_response__free_unpacked
                     (IoctlReadVbattResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ioctl_read_vbatt_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor message__field_descriptors[6] =
{
  {
    "protocol",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Message, protocol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Message, rx_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_flags",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Message, tx_flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Message, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extra_data_index",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Message, extra_data_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Message, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message__field_indices_by_name[] = {
  5,   /* field[5] = data */
  4,   /* field[4] = extra_data_index */
  0,   /* field[0] = protocol */
  1,   /* field[1] = rx_status */
  3,   /* field[3] = timestamp */
  2,   /* field[2] = tx_flags */
};
static const ProtobufCIntRange message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Message",
  "Message",
  "Message",
  "",
  sizeof(Message),
  6,
  message__field_descriptors,
  message__field_indices_by_name,
  1,  message__number_ranges,
  (ProtobufCMessageInit) message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor config__field_descriptors[2] =
{
  {
    "parameter",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Config, parameter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Config, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned config__field_indices_by_name[] = {
  0,   /* field[0] = parameter */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Config",
  "Config",
  "Config",
  "",
  sizeof(Config),
  2,
  config__field_descriptors,
  config__field_indices_by_name,
  1,  config__number_ranges,
  (ProtobufCMessageInit) config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor base_request__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BaseRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BaseRequest, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned base_request__field_indices_by_name[] = {
  1,   /* field[1] = call */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange base_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor base_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BaseRequest",
  "BaseRequest",
  "BaseRequest",
  "",
  sizeof(BaseRequest),
  2,
  base_request__field_descriptors,
  base_request__field_indices_by_name,
  1,  base_request__number_ranges,
  (ProtobufCMessageInit) base_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor base_response__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BaseResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BaseResponse, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BaseResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned base_response__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = code */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange base_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor base_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BaseResponse",
  "BaseResponse",
  "BaseResponse",
  "",
  sizeof(BaseResponse),
  3,
  base_response__field_descriptors,
  base_response__field_indices_by_name,
  1,  base_response__number_ranges,
  (ProtobufCMessageInit) base_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor connect_request__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ConnectRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ConnectRequest, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protocol",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ConnectRequest, protocol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ConnectRequest, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baud",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ConnectRequest, baud),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned connect_request__field_indices_by_name[] = {
  4,   /* field[4] = baud */
  1,   /* field[1] = call */
  3,   /* field[3] = flags */
  0,   /* field[0] = id */
  2,   /* field[2] = protocol */
};
static const ProtobufCIntRange connect_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor connect_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ConnectRequest",
  "ConnectRequest",
  "ConnectRequest",
  "",
  sizeof(ConnectRequest),
  5,
  connect_request__field_descriptors,
  connect_request__field_indices_by_name,
  1,  connect_request__number_ranges,
  (ProtobufCMessageInit) connect_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor connect_response__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ConnectResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ConnectResponse, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ConnectResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ConnectResponse, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned connect_response__field_indices_by_name[] = {
  1,   /* field[1] = call */
  3,   /* field[3] = channel */
  2,   /* field[2] = code */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange connect_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor connect_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ConnectResponse",
  "ConnectResponse",
  "ConnectResponse",
  "",
  sizeof(ConnectResponse),
  4,
  connect_response__field_descriptors,
  connect_response__field_indices_by_name,
  1,  connect_response__number_ranges,
  (ProtobufCMessageInit) connect_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor disconnect_request__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DisconnectRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DisconnectRequest, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DisconnectRequest, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned disconnect_request__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = channel */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange disconnect_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor disconnect_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DisconnectRequest",
  "DisconnectRequest",
  "DisconnectRequest",
  "",
  sizeof(DisconnectRequest),
  3,
  disconnect_request__field_descriptors,
  disconnect_request__field_indices_by_name,
  1,  disconnect_request__number_ranges,
  (ProtobufCMessageInit) disconnect_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor read_request__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ReadRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ReadRequest, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ReadRequest, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ReadRequest, num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ReadRequest, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned read_request__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = channel */
  0,   /* field[0] = id */
  3,   /* field[3] = num */
  4,   /* field[4] = timeout */
};
static const ProtobufCIntRange read_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor read_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ReadRequest",
  "ReadRequest",
  "ReadRequest",
  "",
  sizeof(ReadRequest),
  5,
  read_request__field_descriptors,
  read_request__field_indices_by_name,
  1,  read_request__number_ranges,
  (ProtobufCMessageInit) read_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor read_response__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ReadResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ReadResponse, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ReadResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messages",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ReadResponse, n_messages),
    offsetof(ReadResponse, messages),
    &message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned read_response__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = code */
  0,   /* field[0] = id */
  3,   /* field[3] = messages */
};
static const ProtobufCIntRange read_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor read_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ReadResponse",
  "ReadResponse",
  "ReadResponse",
  "",
  sizeof(ReadResponse),
  4,
  read_response__field_descriptors,
  read_response__field_indices_by_name,
  1,  read_response__number_ranges,
  (ProtobufCMessageInit) read_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor write_request__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(WriteRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(WriteRequest, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(WriteRequest, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messages",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(WriteRequest, n_messages),
    offsetof(WriteRequest, messages),
    &message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(WriteRequest, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_request__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = channel */
  0,   /* field[0] = id */
  3,   /* field[3] = messages */
  4,   /* field[4] = timeout */
};
static const ProtobufCIntRange write_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor write_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WriteRequest",
  "WriteRequest",
  "WriteRequest",
  "",
  sizeof(WriteRequest),
  5,
  write_request__field_descriptors,
  write_request__field_indices_by_name,
  1,  write_request__number_ranges,
  (ProtobufCMessageInit) write_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor write_response__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(WriteResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(WriteResponse, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(WriteResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(WriteResponse, num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_response__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = code */
  0,   /* field[0] = id */
  3,   /* field[3] = num */
};
static const ProtobufCIntRange write_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor write_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WriteResponse",
  "WriteResponse",
  "WriteResponse",
  "",
  sizeof(WriteResponse),
  4,
  write_response__field_descriptors,
  write_response__field_indices_by_name,
  1,  write_response__number_ranges,
  (ProtobufCMessageInit) write_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor start_periodic_request__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartPeriodicRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StartPeriodicRequest, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartPeriodicRequest, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StartPeriodicRequest, message),
    &message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interval",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartPeriodicRequest, interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned start_periodic_request__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = channel */
  0,   /* field[0] = id */
  4,   /* field[4] = interval */
  3,   /* field[3] = message */
};
static const ProtobufCIntRange start_periodic_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor start_periodic_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StartPeriodicRequest",
  "StartPeriodicRequest",
  "StartPeriodicRequest",
  "",
  sizeof(StartPeriodicRequest),
  5,
  start_periodic_request__field_descriptors,
  start_periodic_request__field_indices_by_name,
  1,  start_periodic_request__number_ranges,
  (ProtobufCMessageInit) start_periodic_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor start_periodic_response__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartPeriodicResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StartPeriodicResponse, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartPeriodicResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartPeriodicResponse, message_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned start_periodic_response__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = code */
  0,   /* field[0] = id */
  3,   /* field[3] = message_id */
};
static const ProtobufCIntRange start_periodic_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor start_periodic_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StartPeriodicResponse",
  "StartPeriodicResponse",
  "StartPeriodicResponse",
  "",
  sizeof(StartPeriodicResponse),
  4,
  start_periodic_response__field_descriptors,
  start_periodic_response__field_indices_by_name,
  1,  start_periodic_response__number_ranges,
  (ProtobufCMessageInit) start_periodic_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stop_periodic_request__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StopPeriodicRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StopPeriodicRequest, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StopPeriodicRequest, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StopPeriodicRequest, message_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stop_periodic_request__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = channel */
  0,   /* field[0] = id */
  3,   /* field[3] = message_id */
};
static const ProtobufCIntRange stop_periodic_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor stop_periodic_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StopPeriodicRequest",
  "StopPeriodicRequest",
  "StopPeriodicRequest",
  "",
  sizeof(StopPeriodicRequest),
  4,
  stop_periodic_request__field_descriptors,
  stop_periodic_request__field_indices_by_name,
  1,  stop_periodic_request__number_ranges,
  (ProtobufCMessageInit) stop_periodic_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor start_filter_request__field_descriptors[7] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartFilterRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StartFilterRequest, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartFilterRequest, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filter_type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartFilterRequest, filter_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mask",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StartFilterRequest, mask),
    &message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pattern",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StartFilterRequest, pattern),
    &message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flow_control",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StartFilterRequest, flow_control),
    &message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned start_filter_request__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = channel */
  3,   /* field[3] = filter_type */
  6,   /* field[6] = flow_control */
  0,   /* field[0] = id */
  4,   /* field[4] = mask */
  5,   /* field[5] = pattern */
};
static const ProtobufCIntRange start_filter_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor start_filter_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StartFilterRequest",
  "StartFilterRequest",
  "StartFilterRequest",
  "",
  sizeof(StartFilterRequest),
  7,
  start_filter_request__field_descriptors,
  start_filter_request__field_indices_by_name,
  1,  start_filter_request__number_ranges,
  (ProtobufCMessageInit) start_filter_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor start_filter_response__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartFilterResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StartFilterResponse, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartFilterResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filter_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartFilterResponse, filter_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned start_filter_response__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = code */
  3,   /* field[3] = filter_id */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange start_filter_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor start_filter_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StartFilterResponse",
  "StartFilterResponse",
  "StartFilterResponse",
  "",
  sizeof(StartFilterResponse),
  4,
  start_filter_response__field_descriptors,
  start_filter_response__field_indices_by_name,
  1,  start_filter_response__number_ranges,
  (ProtobufCMessageInit) start_filter_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stop_filter_request__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StopFilterRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StopFilterRequest, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StopFilterRequest, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filter_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StopFilterRequest, filter_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stop_filter_request__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = channel */
  3,   /* field[3] = filter_id */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange stop_filter_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor stop_filter_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StopFilterRequest",
  "StopFilterRequest",
  "StopFilterRequest",
  "",
  sizeof(StopFilterRequest),
  4,
  stop_filter_request__field_descriptors,
  stop_filter_request__field_indices_by_name,
  1,  stop_filter_request__number_ranges,
  (ProtobufCMessageInit) stop_filter_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set_voltage_request__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SetVoltageRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SetVoltageRequest, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pin",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SetVoltageRequest, pin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SetVoltageRequest, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_voltage_request__field_indices_by_name[] = {
  1,   /* field[1] = call */
  0,   /* field[0] = id */
  2,   /* field[2] = pin */
  3,   /* field[3] = voltage */
};
static const ProtobufCIntRange set_voltage_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor set_voltage_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SetVoltageRequest",
  "SetVoltageRequest",
  "SetVoltageRequest",
  "",
  sizeof(SetVoltageRequest),
  4,
  set_voltage_request__field_descriptors,
  set_voltage_request__field_indices_by_name,
  1,  set_voltage_request__number_ranges,
  (ProtobufCMessageInit) set_voltage_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor read_version_response__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ReadVersionResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ReadVersionResponse, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ReadVersionResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReadVersionResponse, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned read_version_response__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = code */
  0,   /* field[0] = id */
  3,   /* field[3] = version */
};
static const ProtobufCIntRange read_version_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor read_version_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ReadVersionResponse",
  "ReadVersionResponse",
  "ReadVersionResponse",
  "",
  sizeof(ReadVersionResponse),
  4,
  read_version_response__field_descriptors,
  read_version_response__field_indices_by_name,
  1,  read_version_response__number_ranges,
  (ProtobufCMessageInit) read_version_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_error_response__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GetErrorResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(GetErrorResponse, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GetErrorResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GetErrorResponse, error),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_error_response__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = code */
  3,   /* field[3] = error */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange get_error_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor get_error_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetErrorResponse",
  "GetErrorResponse",
  "GetErrorResponse",
  "",
  sizeof(GetErrorResponse),
  4,
  get_error_response__field_descriptors,
  get_error_response__field_indices_by_name,
  1,  get_error_response__number_ranges,
  (ProtobufCMessageInit) get_error_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ioctl_request__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IoctlRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IoctlRequest, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IoctlRequest, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ioctl",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IoctlRequest, ioctl),
    &ioctl_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ioctl_request__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = channel */
  0,   /* field[0] = id */
  3,   /* field[3] = ioctl */
};
static const ProtobufCIntRange ioctl_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ioctl_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IoctlRequest",
  "IoctlRequest",
  "IoctlRequest",
  "",
  sizeof(IoctlRequest),
  4,
  ioctl_request__field_descriptors,
  ioctl_request__field_indices_by_name,
  1,  ioctl_request__number_ranges,
  (ProtobufCMessageInit) ioctl_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ioctl_response__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IoctlResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IoctlResponse, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IoctlResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ioctl",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IoctlResponse, ioctl),
    &ioctl_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ioctl_response__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = code */
  0,   /* field[0] = id */
  3,   /* field[3] = ioctl */
};
static const ProtobufCIntRange ioctl_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ioctl_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IoctlResponse",
  "IoctlResponse",
  "IoctlResponse",
  "",
  sizeof(IoctlResponse),
  4,
  ioctl_response__field_descriptors,
  ioctl_response__field_indices_by_name,
  1,  ioctl_response__number_ranges,
  (ProtobufCMessageInit) ioctl_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ioctl_get_config_request__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IoctlGetConfigRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IoctlGetConfigRequest, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IoctlGetConfigRequest, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ioctl",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IoctlGetConfigRequest, ioctl),
    &ioctl_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "config",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(IoctlGetConfigRequest, n_config),
    offsetof(IoctlGetConfigRequest, config),
    &config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ioctl_get_config_request__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = channel */
  4,   /* field[4] = config */
  0,   /* field[0] = id */
  3,   /* field[3] = ioctl */
};
static const ProtobufCIntRange ioctl_get_config_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ioctl_get_config_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IoctlGetConfigRequest",
  "IoctlGetConfigRequest",
  "IoctlGetConfigRequest",
  "",
  sizeof(IoctlGetConfigRequest),
  5,
  ioctl_get_config_request__field_descriptors,
  ioctl_get_config_request__field_indices_by_name,
  1,  ioctl_get_config_request__number_ranges,
  (ProtobufCMessageInit) ioctl_get_config_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ioctl_get_config_response__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IoctlGetConfigResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IoctlGetConfigResponse, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IoctlGetConfigResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ioctl",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IoctlGetConfigResponse, ioctl),
    &ioctl_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "config",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(IoctlGetConfigResponse, n_config),
    offsetof(IoctlGetConfigResponse, config),
    &config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ioctl_get_config_response__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = code */
  4,   /* field[4] = config */
  0,   /* field[0] = id */
  3,   /* field[3] = ioctl */
};
static const ProtobufCIntRange ioctl_get_config_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ioctl_get_config_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IoctlGetConfigResponse",
  "IoctlGetConfigResponse",
  "IoctlGetConfigResponse",
  "",
  sizeof(IoctlGetConfigResponse),
  5,
  ioctl_get_config_response__field_descriptors,
  ioctl_get_config_response__field_indices_by_name,
  1,  ioctl_get_config_response__number_ranges,
  (ProtobufCMessageInit) ioctl_get_config_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ioctl_set_config_request__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IoctlSetConfigRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IoctlSetConfigRequest, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IoctlSetConfigRequest, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ioctl",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IoctlSetConfigRequest, ioctl),
    &ioctl_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "config",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(IoctlSetConfigRequest, n_config),
    offsetof(IoctlSetConfigRequest, config),
    &config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ioctl_set_config_request__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = channel */
  4,   /* field[4] = config */
  0,   /* field[0] = id */
  3,   /* field[3] = ioctl */
};
static const ProtobufCIntRange ioctl_set_config_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ioctl_set_config_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IoctlSetConfigRequest",
  "IoctlSetConfigRequest",
  "IoctlSetConfigRequest",
  "",
  sizeof(IoctlSetConfigRequest),
  5,
  ioctl_set_config_request__field_descriptors,
  ioctl_set_config_request__field_indices_by_name,
  1,  ioctl_set_config_request__number_ranges,
  (ProtobufCMessageInit) ioctl_set_config_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ioctl_read_vbatt_response__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IoctlReadVbattResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IoctlReadVbattResponse, call),
    &call__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IoctlReadVbattResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ioctl",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IoctlReadVbattResponse, ioctl),
    &ioctl_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IoctlReadVbattResponse, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ioctl_read_vbatt_response__field_indices_by_name[] = {
  1,   /* field[1] = call */
  2,   /* field[2] = code */
  0,   /* field[0] = id */
  3,   /* field[3] = ioctl */
  4,   /* field[4] = voltage */
};
static const ProtobufCIntRange ioctl_read_vbatt_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ioctl_read_vbatt_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IoctlReadVbattResponse",
  "IoctlReadVbattResponse",
  "IoctlReadVbattResponse",
  "",
  sizeof(IoctlReadVbattResponse),
  5,
  ioctl_read_vbatt_response__field_descriptors,
  ioctl_read_vbatt_response__field_indices_by_name,
  1,  ioctl_read_vbatt_response__number_ranges,
  (ProtobufCMessageInit) ioctl_read_vbatt_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue call__enum_values_by_number[13] =
{
  { "InvalidCall", "CALL__InvalidCall", 0 },
  { "Connect", "CALL__Connect", 1 },
  { "Disconnect", "CALL__Disconnect", 2 },
  { "Read", "CALL__Read", 3 },
  { "Write", "CALL__Write", 4 },
  { "StartPeriodic", "CALL__StartPeriodic", 5 },
  { "StopPeriodic", "CALL__StopPeriodic", 6 },
  { "StartFilter", "CALL__StartFilter", 7 },
  { "StopFilter", "CALL__StopFilter", 8 },
  { "SetVoltage", "CALL__SetVoltage", 9 },
  { "ReadVersion", "CALL__ReadVersion", 10 },
  { "GetError", "CALL__GetError", 11 },
  { "Ioctl", "CALL__Ioctl", 12 },
};
static const ProtobufCIntRange call__value_ranges[] = {
{0, 0},{0, 13}
};
static const ProtobufCEnumValueIndex call__enum_values_by_name[13] =
{
  { "Connect", 1 },
  { "Disconnect", 2 },
  { "GetError", 11 },
  { "InvalidCall", 0 },
  { "Ioctl", 12 },
  { "Read", 3 },
  { "ReadVersion", 10 },
  { "SetVoltage", 9 },
  { "StartFilter", 7 },
  { "StartPeriodic", 5 },
  { "StopFilter", 8 },
  { "StopPeriodic", 6 },
  { "Write", 4 },
};
const ProtobufCEnumDescriptor call__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Call",
  "Call",
  "Call",
  "",
  13,
  call__enum_values_by_number,
  13,
  call__enum_values_by_name,
  1,
  call__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ioctl_id__enum_values_by_number[14] =
{
  { "InvalidIoctl", "IOCTL_ID__InvalidIoctl", 0 },
  { "GetConfig", "IOCTL_ID__GetConfig", 1 },
  { "SetConfig", "IOCTL_ID__SetConfig", 2 },
  { "ReadVbatt", "IOCTL_ID__ReadVbatt", 3 },
  { "FiveBaudInit", "IOCTL_ID__FiveBaudInit", 4 },
  { "FastInit", "IOCTL_ID__FastInit", 5 },
  { "ClearTxBuffer", "IOCTL_ID__ClearTxBuffer", 7 },
  { "ClearRxBuffer", "IOCTL_ID__ClearRxBuffer", 8 },
  { "ClearPeriodic", "IOCTL_ID__ClearPeriodic", 9 },
  { "ClearFilters", "IOCTL_ID__ClearFilters", 10 },
  { "ClearLUT", "IOCTL_ID__ClearLUT", 11 },
  { "AddLUT", "IOCTL_ID__AddLUT", 12 },
  { "DeleteLUT", "IOCTL_ID__DeleteLUT", 13 },
  { "ReadVoltage", "IOCTL_ID__ReadVoltage", 14 },
};
static const ProtobufCIntRange ioctl_id__value_ranges[] = {
{0, 0},{7, 6},{0, 14}
};
static const ProtobufCEnumValueIndex ioctl_id__enum_values_by_name[14] =
{
  { "AddLUT", 11 },
  { "ClearFilters", 9 },
  { "ClearLUT", 10 },
  { "ClearPeriodic", 8 },
  { "ClearRxBuffer", 7 },
  { "ClearTxBuffer", 6 },
  { "DeleteLUT", 12 },
  { "FastInit", 5 },
  { "FiveBaudInit", 4 },
  { "GetConfig", 1 },
  { "InvalidIoctl", 0 },
  { "ReadVbatt", 3 },
  { "ReadVoltage", 13 },
  { "SetConfig", 2 },
};
const ProtobufCEnumDescriptor ioctl_id__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "IoctlId",
  "IoctlId",
  "IoctlId",
  "",
  14,
  ioctl_id__enum_values_by_number,
  14,
  ioctl_id__enum_values_by_name,
  2,
  ioctl_id__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
